In [1]:
import numpy as np

In [272]:
#array can accept one data type where as list can accept different types
n=np.array([1,2,3,4])
m=np.array([1,2,'k',4])

In [6]:
m=np.array([1,2,'k',4])
m

array(['1', '2', 'k', '4'], dtype='<U11')

In [9]:
n=np.array([1,2,3,4],dtype=np.float32)
n


array([1., 2., 3., 4.], dtype=float32)

In [15]:
#range is a function generating seq of nos startng from 
n=np.array(range(10))
n
#checking dim of array
n.ndim
#making array of 2 d
n=np.array([[1,2],[3,4]])
print(n)

[[1 2]
 [3 4]]


In [274]:
np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [19]:
#having 1s in the diagonal
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
#having nos specified in []
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [26]:
#range version in numpy is arrange
np.arange(10)
np.arange(5,10)
np.arange(0,10,3)#3 for the step size
np.arange(0,10,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [29]:
#allows you to give equal width segmnet . no=last 
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [50]:
n1=np.array([[1,2],[3,4]])
n1

array([[1, 2],
       [3, 4]])

In [51]:
n2=np.tile(n1,(3,2))
n2

array([[1, 2, 1, 2],
       [3, 4, 3, 4],
       [1, 2, 1, 2],
       [3, 4, 3, 4],
       [1, 2, 1, 2],
       [3, 4, 3, 4]])

In [52]:
n2.ndim

2

In [53]:
n2.shape

(6, 4)

In [54]:
#elements in array
n2.size

24

In [55]:
n2.astype(np.float32)

array([[1., 2., 1., 2.],
       [3., 4., 3., 4.],
       [1., 2., 1., 2.],
       [3., 4., 3., 4.],
       [1., 2., 1., 2.],
       [3., 4., 3., 4.]], dtype=float32)

In [276]:
#changing shape of array
n=np.array([[1,2,3],
            [4,5,6],
           [7,8,9]])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [277]:
n.shape

(3, 3)

In [278]:
#changing the shape of the array
n.reshape(9,1)
n.reshape(1,9)
#2 brackets mean 2 dimension

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [73]:
n.resize((1,9))
n

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [71]:
n.ndim
n.shape

(1, 9)

In [88]:
a=np.array([1,2])
b=np.array([[5,6],[7,8]])
a

array([1, 2])

In [90]:
a+b

array([[ 6,  8],
       [ 8, 10]])

In [87]:
a.T

array([[ 1,  9],
       [ 4, 16]])

In [91]:
a=np.array([[1,1],[0,1]])
b=np.array([[2,0],[3,4]])

In [92]:
a.dot(b)

array([[5, 4],
       [3, 4]])

In [98]:
#universal function
a=np.array([[1,2],[3,4]])
n2=np.sqrt(a)

In [100]:
np.round(n2,2)

array([[1.  , 1.41],
       [1.73, 2.  ]])

In [106]:
a=np.arange(10)
a.sum()
a.max()
a.std()

2.8722813232690143

In [280]:
n=np.arange(12)
n1=n.reshape(4,3)
n1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [116]:
#np.cumsum(n)
np.cumsum(n1,axis=0)#axis=0 by col vertically


array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21],
       [ 9, 19, 30]], dtype=int32)

In [118]:
#iterating through each number
#be default it is iterate by row
for i in n1:
    print(i)
    print('---')

[0 1 2]
---
[3 4 5]
---
[6 7 8]
---
[ 9 10 11]
---


In [137]:
for i in n1:
    print(i)
    print(i.ndim)
    print(type(i))
    for j in i:
        print(j)
        print(type(j))
        print('---')

[0 1 2]
1
<class 'numpy.ndarray'>
0
<class 'numpy.int32'>
---
1
<class 'numpy.int32'>
---
2
<class 'numpy.int32'>
---
[3 4 5]
1
<class 'numpy.ndarray'>
3
<class 'numpy.int32'>
---
4
<class 'numpy.int32'>
---
5
<class 'numpy.int32'>
---
[6 7 8]
1
<class 'numpy.ndarray'>
6
<class 'numpy.int32'>
---
7
<class 'numpy.int32'>
---
8
<class 'numpy.int32'>
---
[ 9 10 11]
1
<class 'numpy.ndarray'>
9
<class 'numpy.int32'>
---
10
<class 'numpy.int32'>
---
11
<class 'numpy.int32'>
---


In [139]:
'''
for i in n1:
    for j in i:
        print(j)
        print('---')'''
#OR
for i in n1.flat:
    print(i)
    

0
1
2
3
4
5
6
7
8
9
10
11


In [123]:
n1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [128]:
np.apply_along_axis(np.sum,axis=1,arr=n1)

array([ 3, 12, 21, 30])

In [147]:
np.random.seed(10)
np.random.random(10)

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701,
       0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981])

In [153]:
np.random.random((3,3))#nos only between 0 an 1
np.random.randn(3)
np.random.randint(10,20,5)#will give 5 random no between 10,20 exclusive 20 inlcusidng 10

array([19, 11, 18, 19, 11])

In [159]:
np.random.randint(10,20,(4,4))#will give 4,4 matrix no between 10,20 exclusive 20 inlcusidng 10

array([[15, 18, 19, 19, 11, 15, 19, 11],
       [14, 17, 17, 17, 19, 17, 16, 10]])

In [164]:
#it creates normal distribution with mean 0 
np.random.randn(100)
#for matrix generatuon
np.random.randn(4,2,3)

array([[[-1.19774694, -1.07573673, -1.14416629],
        [ 0.49063171, -0.2816296 ,  1.47512411]],

       [[-1.26069282,  0.96764905, -0.58862765],
        [ 0.56521794,  0.58509769,  0.07776516]],

       [[-0.09697364,  0.36008527,  0.26140708],
        [-0.70170471, -0.31720219,  0.47544377]],

       [[-0.93211461, -0.96653955,  0.78771417],
        [ 1.9046969 ,  0.15158769, -0.50177628]]])

In [156]:
np.random.random(4)

array([0.23264106, 0.55651819, 0.52381088, 0.35095822])

In [169]:
#index slicing
n1.shape[0]

4

In [171]:
n1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [173]:
#last row
n1[n1.shape[0]-1]
n1[-1]
n1[-1][1]

10

In [176]:
n=np.arange(100).reshape(10,10)
n

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [183]:
n[0:3,-3:-1]#0 and -3 are inclusive and 3 and -1 are exclusive

array([[ 7,  8],
       [17, 18],
       [27, 28]])

In [184]:
n[0:0,-3:-1]

array([], shape=(0, 2), dtype=int32)

In [186]:
n[3:6,:]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [196]:

n[[1,2],[1,2]]
n

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [197]:
n[[1,2],[1,2]]

array([11, 22])

In [198]:
n1=np.random.randint(0,25,10)
n1[n1>10]=10
n1

In [210]:
a=np.array([1,2,3])
b=a

In [213]:
b

array([1, 2, 3])

In [212]:
a[0]=22

In [211]:
#if one variable is creatde using = it means it is pointing to sma ephysical location
#but with a.copy() it does not change
b=a.copy()

In [217]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
n2=np.append(a,b)
n2=np.append(a,b,axis=1)

In [227]:
n3=np.insert(a,1,[100,101])
n3=np.insert(a,1,[100,101],axis=1)

In [231]:
np.vstack((a,b)) 
#OR 
np.column_stack((a,b))

np.hstack((a,b))
#OR
np.row_stack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [232]:
##diff
c=np.array([1,2,3,4])
d=np.array([5,6,7,8])

In [233]:
np.vstack((c,d))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [234]:
np.hstack((c,d))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [235]:
np.column_stack((c,d))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [236]:
np.row_stack((c,d))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [238]:
##array splitting
n=np.arange(16).reshape(4,4)
n

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [239]:
a,b=np.hsplit(n,2)
a

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [244]:
x=np.hsplit(n,4)
x[0]

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [ ]:
#saving as .npy file it is a binary file


In [248]:
path ='D:\\Users\\hacma0b\\Documents\\Juhi_doc\\Training and Material\\Practice\\PythonTraining\\samplesFiles - AIA\\'
#np.save('myData.npy')
file=path + 'myData.npy'
np.save(file,n)

In [249]:
#load file
b=np.load(file)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [252]:
dir2 ='D:\\Users\\hacma0b\\Documents\\Juhi_doc\\Training and Material\\Practice\\PythonTraining\\samplesFiles - AIA\\samplesFiles - AIA\\'
file=dir2+'data2Numpy.csv'
file

'D:\\Users\\hacma0b\\Documents\\Juhi_doc\\Training and Material\\Practice\\PythonTraining\\samplesFiles - AIA\\samplesFiles - AIA\\data2Numpy.csv'

In [257]:
n=np.genfromtxt(file,delimiter=',',names=True)
n

array([(98., 100., 86.), (24.,  23., 99.), ( 1.,  41., 17.),
       (84.,  34.,  2.), (43.,  -1., 99.)],
      dtype=[('a', '<f8'), ('b', '<f8'), ('c', '<f8')])

In [270]:
np.array([('1',2),('a',3)])

array([['1', '2'],
       ['a', '3']], dtype='<U1')

In [267]:
one=[1,2]
two=['a','b']
n5=np.array([one,two])

In [264]:
dir2 ='D:\\Users\\hacma0b\\Documents\\Juhi_doc\\Training and Material\\Practice\\PythonTraining\\samplesFiles - AIA\\samplesFiles - AIA\\'
file=dir2+'ebay_label.csv'
n1=np.genfromtxt(file,delimiter=',',names=True)
n1

array([(nan, nan, 153.35, 153.93  , 153.06, 153.5 , 153.5 , 12778195.),
       (nan, nan, 151.8 , 153.84  , 151.8 , 152.74, 152.74, 18714400.),
       (nan, nan, 150.58, 152.44  , 149.9 , 152.09, 152.09, 21304700.),
       (nan, nan, 149.99, 150.44  , 148.88, 150.27, 150.27, 26252630.),
       (nan, nan, 151.5 , 151.74  , 150.19, 150.34, 150.34, 17243748.),
       (nan, nan, 150.48, 151.42  , 149.95, 151.02, 151.02, 20922969.),
       (nan, nan, 149.2 , 150.13  , 148.67, 150.08, 150.08, 17868792.),
       (nan, nan, 148.82, 150.9   , 148.57, 149.56, 149.56, 23243713.),
       (nan, nan, 147.97, 149.33  , 147.33, 149.04, 149.04, 20132061.),
       (nan, nan, 145.5 , 148.49  , 145.44, 147.77, 147.77, 25199373.),
       (nan, nan, 145.87, 146.18  , 144.82, 145.74, 145.74, 24884478.),
       (nan, nan, 144.73, 145.85  , 144.38, 145.53, 145.53, 19781836.),
       (nan, nan, 144.11, 145.95  , 143.37, 145.06, 145.06, 21090636.),
       (nan, nan, 142.9 , 144.75  , 142.9 , 144.18, 144.18, 1920

In [271]:
n5=np.array(n1[0])

(nan, nan, 153.35, 153.93, 153.06, 153.5, 153.5, 12778195.)

In [144]:

dir2 ='D:\\Users\\hacma0b\\Documents\\Juhi_doc\\Training and Material\\Practice\\PythonTraining\\samplesFiles - AIA\\samplesFiles - AIA\\'

dir ='D:\\Users\\hacma0b\\Documents\\Juhi_doc\\Training and Material\\Practice\\PythonTraining\\samplesFiles - AIA\\'