In [2]:
import pandas as pd
import numpy as np


In [42]:
list1=[1,2,3,4]
numpyarray=np.array(list1)
#print(numpyarray)
numpyarray.shape

num2=np.array([[1,2,3],[4,5,6]])
print(num2[0:2,0:3])

[[1 2 3]
 [4 5 6]]


In [16]:
height=np.round(np.random.normal(1.75,0.20,5),2)
weight=np.round(np.random.normal(60.32,15,5),2)
np_city=np.column_stack((height,weight))
print(np_city)

[[  1.47  76.88]
 [  1.77  65.11]
 [  1.7   77.3 ]
 [  1.69  50.5 ]
 [  1.76  77.85]]


In [18]:
s=pd.Series([1,3,5,np.nan,6,8])
print(s)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64


In [21]:
dates=pd.date_range(start='2018-04-01',periods=6)
print(dates)
type(dates)

DatetimeIndex(['2018-04-01', '2018-04-02', '2018-04-03', '2018-04-04',
               '2018-04-05', '2018-04-06'],
              dtype='datetime64[ns]', freq='D')


pandas.core.indexes.datetimes.DatetimeIndex

In [23]:
np.random.randn(6,4)


array([[-0.71911752, -0.69869462, -0.22517818, -0.22360123],
       [ 0.2542227 ,  1.39508622,  1.2392115 ,  0.77649145],
       [-0.82155193,  0.05834963, -1.52652715,  0.67238362],
       [-1.34687585, -0.68201478, -0.74534657,  1.37688868],
       [ 0.45358111,  1.17014018, -0.4073263 ,  0.5552401 ],
       [-0.43117084, -0.11765977,  0.87311182,  0.77305017]])

In [32]:
#np.random.randn(6,4) creates a matrix of 6 rows and 4 cols
#pd.dataframe(data,index,columns)# columns=list('ABCD')/columns=['A','B','C','D']
df=pd.DataFrame(np.random.randn(6,4), index=dates, columns=['first','sec','third','fourth'])
print(df)

               first       sec     third    fourth
2018-04-01  0.271576 -0.168108  0.183074 -0.809681
2018-04-02 -1.847412  1.490701  0.015896 -1.949742
2018-04-03  0.877607 -1.212166 -0.763250  1.476495
2018-04-04  1.715302 -2.097094 -0.101530 -1.536663
2018-04-05  1.656970 -0.882775 -0.756111 -0.914346
2018-04-06 -0.049110 -0.761084 -0.874341  1.160255


In [44]:
#DataFrame can be created by passing a dict of objects that can be converted to series-like
df2 = pd.DataFrame({ 'A' : 1.,
'B' : pd.Timestamp('20130102'),
'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
'D' : np.array([3] * 4,dtype='int32'),
'E' : pd.Categorical(["test","train","test","train"]),
'F' : 'foo' 
                   } )
print(df2)

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo


In [61]:
#df.describe
#df.T #Transpose data frame
#df.sort_index(axis=1, ascending=False)
#df['first']
df[0:3]

first       sec     third    fourth
2018-04-01  0.271576 -0.168108  0.183074 -0.809681
2018-04-02 -1.847412  1.490701  0.015896 -1.949742
2018-04-03  0.877607 -1.212166 -0.763250  1.476495

In [13]:
# to import file in python import csv package, \\ is necessary in path otherwise it will consider \ as escape character
# another way is using pandas pd.read_csv('file name')
import csv
f=open('C:\\Users\\Juhi.Agarwal\\Python\\AnalyticsVidhya\\train_u6lujuX_CVtuZ9i.csv','r+')

readFile=csv.reader(f)
for jt in readFile:
    print(jt[1])
    
    

SyntaxError: unexpected EOF while parsing (<ipython-input-13-587abbcde1b5>, line 10)

In [3]:
df=pd.read_csv('C:\\Users\\Juhi.Agarwal\\Python\\AnalyticsVidhya\\train_u6lujuX_CVtuZ9i.csv')
df.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [17]:
df.describe()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count       614.000000         614.000000  592.000000         600.00000   
mean       5403.459283        1621.245798  146.412162         342.00000   
std        6109.041673        2926.248369   85.587325          65.12041   
min         150.000000           0.000000    9.000000          12.00000   
25%        2877.500000           0.000000  100.000000         360.00000   
50%        3812.500000        1188.500000  128.000000         360.00000   
75%        5795.000000        2297.250000  168.000000         360.00000   
max       81000.000000       41667.000000  700.000000         480.00000   

       Credit_History  
count      564.000000  
mean         0.842199  
std          0.364878  
min          0.000000  
25%          1.000000  
50%          1.000000  
75%          1.000000  
max          1.000000

In [44]:
df['Gender'].value_counts()

Male      489
Female    112
Name: Gender, dtype: int64

In [23]:
df.count(axis=0)

Loan_ID              614
Gender               601
Married              611
Dependents           599
Education            614
Self_Employed        582
ApplicantIncome      614
CoapplicantIncome    614
LoanAmount           592
Loan_Amount_Term     600
Credit_History       564
Property_Area        614
Loan_Status          614
dtype: int64

In [31]:
#arr = np.array([1, 2, 3, 4])
#arr.dtype.name
cat = pd.Categorical(['a', 'b', 'c'])
cat.dtype.name

'category'

In [32]:
def is_categorical(array_like):
    return array_like.dtype.name == 'category'

In [35]:
#to check single column wether categorical or not
#pd.core.common.is_categorical_dtype(df.Married)

False

In [41]:
##2.data cleaning step1
##categorising between numeric and categorical columns
#getting columns 
cols=df.columns
#print(cols)
num_cols = df._get_numeric_data().columns#grtting numeric columns
#print(num_cols)
cat_cols=list(set(cols) - set(num_cols))
print(cat_cols)

['Property_Area', 'Dependents', 'Loan_ID', 'Self_Employed', 'Married', 'Gender', 'Education', 'Loan_Status']


In [63]:
df['Gender']#selecting 1 particular col

df[0:1]#slicing the rows
#df.index
df.loc[0]#selection by label if label name not there if label anme there then df.loc[dates[0]]
df.loc[:,['Gender','Married']]#selecting GEnder and married col for all the label rows
df.loc[1:3,['Gender','Married']]#col and row selection
df.loc[1,['Gender','Married']]

Gender     Male
Married     Yes
Name: 1, dtype: object

In [66]:
df.iloc[2:3,:]# using position for rows and columns
df.iloc[[1,2,6],[1,5]]#using specific columns

Gender Self_Employed
1   Male            No
2   Male           Yes
6   Male            No

In [84]:
#Boolean Indexing
df[df.Gender!='Male']
#df2=df.copy()
#df2('testcol')=[1,2,3]you can assign values to a new col
df[df['Gender'].isin(['Male'])] filetring values of a col by isin()

In [87]:
pd.isna(df)

AttributeError: module 'pandas' has no attribute 'isna'

In [15]:
#data manipulation practice
#eg: all females who are nt graduate, but have got a loan
df.loc[(df["Gender"]=="Female") & (df["Education"]=="Not Graduate") & (df["Loan_Status"]=="Y"),["Gender","Education","Loan_Status"]]

#for missing values
def num_missing(x):
    return sum(x.isnull())

#applying per columsn
print("missing values in cols")
print(df.apply(num_missing,axis=0))

missing values in cols
Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64
